trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - irb120_controller
  - egp64_finger_left_controller
  - egp64_finger_right_controller

irb120_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

egp64_finger_left_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - egp64_finger_left_joint

egp64_finger_right_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - egp64_finger_right_joint