string type                         # Input to RobMove -> Type of MOVEMENT: PTP/LIN.
float64 speed                       # Input to RobMove -> Robot movement SPEED.
float64 x                           # Input to RobMove -> POSE-POSITION-(x)COORDINATE.
float64 y                           # Input to RobMove -> POSE-POSITION-(y)COORDINATE.
float64 z                           # Input to RobMove -> POSE-POSITION-(z)COORDINATE.
float64 qx                          # Input to RobMove -> POSE-ORIENTATION-QUATERNION(x).
float64 qy                          # Input to RobMove -> POSE-ORIENTATION-QUATERNION(y).
float64 qz                          # Input to RobMove -> POSE-ORIENTATION-QUATERNION(z).
float64 qw                          # Input to RobMove -> POSE-ORIENTATION-QUATERNION(w).
---
bool success                        # RobMove-> Successful? True/False.
string message                      # Result MESSAGE -> Information about ROBOT MOVEMENT.
---
string feedback                     # NOT NEEDED.