# ROS 2 Sim-to-Real Robot Control: KUKA LBR-IIWA Robot.
Configurations:

  - ID: "iiwa_1"
    Name: "KUKA LBR-IIWA on top of Robot Stand."
    urdf: "iiwa.urdf.xacro"
    rob: "iiwa"
    ee: "none"

  - ID: "iiwa_2"
    Name: "KUKA LBR-IIWA + Robotiq 2f-85 Gripper on top of Robot Stand."
    urdf: "iiwa_robotiq_2f85.urdf.xacro"
    rob: "iiwa"
    ee: "robotiq_2f85"