# ROS 2 Sim-to-Real Robot Control: ABB IRB-120 Robot.
Configurations:

  - ID: "irb120_1"
    Name: "ABB IRB-120 on top of Robot Stand."
    urdf: "irb120.urdf.xacro"
    rob: "irb120"
    ee: "none"

  - ID: "irb120_2"
    Name: "ABB IRB-120 + Schunk EGP-64 Gripper on top of Robot Stand."
    urdf: "irb120_egp64.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "irb120_21"
    Name: "ABB IRB-120 + Schunk EGP-64 Gripper (rounded fingers) on top of Robot Stand."
    urdf: "irb120_egp64v2.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "irb120_3"
    Name: "ABB IRB-120 + Lamination Sheet Vacuum-Gripper on top of Robot Stand."
    urdf: "irb120_ls_vgr.urdf.xacro"
    rob: "irb120"
    ee: "ls_vgr"