joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 17.4532
  joint_2:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 17.4532
  joint_3:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 17.4532
  joint_4:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 22.3402
  joint_5:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 22.3402
  joint_6:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: true
    max_acceleration: 29.3216
  joint_7:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: true
    max_acceleration: 29.3216