joint_limits:
  robotiq_hande_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00
  robotiq_hande_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00