trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - ur_controller
  - robotiq_controller_LKJ
  - robotiq_controller_RKJ
  - robotiq_controller_LIKJ
  - robotiq_controller_RIKJ
  - robotiq_controller_LFTJ
  - robotiq_controller_RFTJ

ur_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

robotiq_controller_LKJ:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - robotiq_85_left_knuckle_joint

robotiq_controller_RKJ:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - robotiq_85_right_knuckle_joint

robotiq_controller_LIKJ:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - robotiq_85_left_inner_knuckle_joint

robotiq_controller_RIKJ:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - robotiq_85_right_inner_knuckle_joint

robotiq_controller_LFTJ:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - robotiq_85_left_finger_tip_joint

robotiq_controller_RFTJ:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - robotiq_85_right_finger_tip_joint