joint_limits:
  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00
  robotiq_85_right_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00
  robotiq_85_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00
  robotiq_85_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00
  robotiq_85_left_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00
  robotiq_85_right_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 1.00