# ROS 2 Sim-to-Real Robot Control: ABB IRB-120 Robot.
Configurations:

  - ID: "irb1200_1"
    Name: "ABB IRB-1200 on top of Robot Stand."
    urdf: "irb1200.urdf.xacro"
    ee: "none"

  - ID: "irb1200_2"
    Name: "ABB IRB-1200 + Schunk EGP-64 Gripper on top of Robot Stand."
    urdf: "irb1200egp64.urdf.xacro"
    ee: "egp64"