# ROS 2 Sim-to-Real Robot Control: ABB IRB-120 Robot.
Configurations:

  - ID: "irb120_1"
    Name: "ABB IRB-120 on top of Robot Stand."
    urdf: "irb120.urdf.xacro"
    ee: "none"

  - ID: "irb120_2"
    Name: "ABB IRB-120 + Schunk EGP-64 Gripper on top of Robot Stand."
    urdf: "irb120_egp64.urdf.xacro"
    ee: "egp64"